### ISSUE TITLE
Adding support for osx-arm64

### ISSUE THREAD

**Issue by PertuyF** [conda-forge/firefox-feedstock#117]
### Comment:

See PR https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3913

**Comment by bollwyvl** [comment]
I'm happy to merge #118, but have no way to test it: please report back with any findings.

**Comment by bollwyvl** [comment]
I've opened #119 for `108.0.1`, which would be a good place to fix anything reported from the #118 build.

**Comment by PertuyF** [comment]
I can confirm firefox `108.0` has been built (build number `hb7217d7_0`) for `osx-arm64` platform, and it is working as expected. So #118 is a success as far as I'm concerned.

**Comment by bollwyvl** [comment]
Great, thanks for the review. I guess open a new issue for anything else!
